# Site settings
title: BMS Datasets
description: > # this means to ignore newlines until "baseurl:"
  Find datasets from the Department of Energy
  to hack on your latest project.
  This project is not associated with the Department of Energy.
baseurl: "/bmsdatasets" # the subpath of your site, e.g. /blog/
url: "https://ami-solution.github.io/bmsdatasets" # the base hostname & protocol for your site
twitter_username: ossbss_ami_ucc
#github_username:  jekyll
permalink: /:title.html

# Build settings
markdown: kramdown

collections:
 datasets:
  output: true
  permalink: /d/:title.html
